apiVersion: v1
kind: Pod
spec:
  containers:
    - name: buildah
      image: m4xmoehl/buildah:0.1.0
      securityContext:
        privileged: true
      command:
        - sleep
      args:
        - infinity
