apiVersion: v1
kind: Pod
spec:
  containers:
    - name: buildah
      image: registry:5000/buildah:0.1.1
      securityContext:
        privileged: true
      command:
        - sleep
      args:
        - infinity
